=== osiota/osiota/schema_config.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"description": "schema for an energy router config file",
	"type": "object",
	"required": [ "hostname" ],
	"title": "energy-router configuration",
	"properties": {
		"hostname": {
			"type": "string"
		},
		"server": {
			"type": "number"
		},
		"connect": {
			"type": "object",
			"title": "Connect nodes to each other",
			"patternProperties": {
				"^(.+)$": {
					"type": "object",
					"properties": {
						"target": {
							"type": "string"
						}
					},
					"required": ["target"]
				}
			},
			"additionalProperties": true,
			"options": {
				"disable_properties": false,
				"disable_edit_json": false
			}
		},
		"remote": {
			"type": "array",
			"title": "Remotes",
			"format": "table",
			"items": {
				"type": "object",
				"title": "Remote",
				"properties": {
					"name": {
						"type": "string",
						"default": "remote"
					},
					"url": {
						"type": "string",
						"pattern": "^ws(s)?://[a-zA-Z0-9-_.]+(:[0-9]+)?(/.*)?$"
					},
					"node": {
						"type": "string",
						"default": "/"
					}
				},
				"required": ["name", "url"]
			}
		},
		"app": {
			"type": "array",
			"title": "Applications",
			"format": "tabs",
			"keep_oneof_values": false,
			"items": {
				"type": "object",
				"title": "Application",
				"oneOf": [
				]
			}
		}
	}
}

=== osiota/osiota/config_demo_icce.json
{
	"hostname": "ifn-cluster",
	"server": 8080,
	"remote": [
	],
	"app": [
		{
			"name": "er-app-tubs-extradata",
			"config": {}
		},
		{
			"name": "er-app-icce-demo",
			"config": {}
		},
		{
			"name": "er-app-analysis",
			"config": {}
		},
		{
			"name": "er-app-peak-manager",
			"config": {}
		}
	]
}
